services:
    awsimg-node:
        container_name: awsimg-node
        build: ./node
        ports:
            - "3420:3420"
        networks:
            - awsimg-network
        volumes:
            - ../..:/workspace/aws-lambda-resize
        command: /bin/bash /root/start.sh

    awsimg-nginx:
        container_name: awsimg-nginx
        build: ./nginx
        ports:
            - "420:420"
        links:
            - awsimg-node
        volumes:
            - ./nginx/etc-nginx-sites-enabled:/etc/nginx/sites-enabled
            - ../..:/workspace/aws-lambda-resize
        networks:
            - awsimg-network

networks:
    awsimg-network:
